[project]
name = 'Decentralized-Microinsurance-for-Low-Income-Communities'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.claims-processing]
path = 'contracts/claims-processing.clar'
clarity_version = 2
epoch = 2.5

[contracts.peer-verification]
path = 'contracts/peer-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.policy-creation]
path = 'contracts/policy-creation.clar'
clarity_version = 2
epoch = 2.5

[contracts.premium-collection]
path = 'contracts/premium-collection.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
